import type { Metadata } from "next";
import { Albert_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const albertSans = Albert_Sans({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--font-albert",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Project Next App",
  description: "Generated by project next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${albertSans.variable} h-full antialiased`}>
      <body className="flex flex-col body">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
